#!/bin/sh

set -u
export PATH="/bin:/usr/bin:/sbin:/usr/sbin"

uid=$(id -u "$PAM_USER") || exit $?

keyctl padd user "user:$uid" @u || exit $?
systemctl start "homedir@$uid.service" || exit $?

exit 0

