- name: "udev rules for Android"
  sudo: true
  copy:
    src: udev.android.rules
    dest: /etc/udev/rules.d/51-android.rules
    mode: 0644
    owner: root
    group: root
  notify: "udevd reload"

