- name: "Install packages"
  apt:
    name: "{{item}}"
    state: latest
    update_cache: false
  with_items:
    - pdns-recursor
  become: true

- name: "Install configuration files"
  copy:
    src: "{{item}}"
    dest: /etc/powerdns/
    mode: 0444
    owner: root
    group: root
    backup: false
  become: true
  notify: "PowerDNS Recursor: Restart"
  with_items:
    - powerdns/recursor/recursor.conf
    - powerdns/recursor/recursor.lua
    - powerdns/recursor/hosts

- name: "Start service"
  service:
    name: pdns-recursor
    state: running
    enabled: true
  become: true
